# Copyright 2021 Ubuntu
# See LICENSE file for licensing details.
#

options:
  url:
    description: url of the existing Rancher platform against which registration will be performed.
    type: string
    default: changeme
  bearer-token:
    description: bearer-token needed to access the Rancher api.
    type: string
    default: change:me
  cert-verify:
    default: 'True'
    description: |
      Toggles verification of the Rancher platform certificate. Setting this to 'False' is not
      recommended but can be useful for development purposes when using a self-signed certificate.
    type: string