# Copyright 2021 Ubuntu
# See LICENSE file for licensing details.
#

options:
  url:
    description: url of the existing Rancher platform against which registration will be performed.
    type: string
  bearer-token:
    description: bearer-token needed to access the Rancher api.
    type: string
  cert-verify:
    default: true
    description: |
      Disables verification of the Rancher platform certificate. This is not recommended but can be
      useful for development purposes when using a self-signed certificate.
    type: boolean
  cluster-name:
    description: |
      User defined cluster name to be used within the Rancher platform. If this option is not set,
      a randomly generated cluster name will be assigned.
    type: string
